providers = ["php"]

[phases.install]
  cmds = ["npm install", "composer install --no-dev --optimize-autoloader"]

[phases.build]
  cmds = ["npm run build"]

[phases.setup]
  cmds = [
    "mkdir -p storage/framework/views storage/framework/cache/data storage/framework/sessions storage/logs storage/app/public",
    "chmod -R 775 storage",
    "php artisan storage:link --force",
    "php artisan optimize",
  ]
