# nixpacks.toml
providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.bcmath", "php83Extensions.intl", "php83Extensions.gd", "php83Packages.composer"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader --no-interaction --no-progress",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan storage:link && nginx -c /app/nginx.conf"